# server
server:
  port: 9010

# logging
logging:
  level:
    com.kakao.insurance: debug
    org.hibernate.SQL: debug

# spring
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem::kakao-insurance
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS


